# Setup
title:               JSBlogs
tagline:             ''
description:         'Hi!!,<br/>I am Jitendra Singh Bisht and this is my personal blog. I&#x27;m a tech enthusiast and love reading about new tech.'
url:                 https://blogs.jsbisht.com
baseurl:             '' #base url
paginate:            5
#permalink:           pretty
permalink:            /:categories/:year/:month/:day/:title

# About/contact
author:
  name:              Jitendra Singh Bisht
  url:               https://blogs.jsbisht.com
  email:             jeet.mp3@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

include:
  - _headers

  # Custom vars
version:             1.1.0
owner:
  disqus-shortname: blogs-jbisht-com
  twitter: JitendraBisht3
  facebook: 100001590673679
  github: jeetmp3
  stackexchange: https://stackoverflow.com/users/1739365/jitendra
  linkedin: jitendra-bisht-a7a25845
  instagram: jeet.mp3
  google:
    plus: JITTUBISHT
    analytics: UA-83820107-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
