# Setup
title:               JSBlogs
tagline:             ''
description:         'Hi,<br/>I am Jitendra Singh Bisht and this is my personal blog. I&#x27;m a tech enthusiast and love reading about new tech.'
url:                 https://jsblogs.github.io
baseurl:             '' #base url
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jitendra Singh Bisht
  url:               https://jsblogs.github.io
  email:             jeet.mp3@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
